spring:
    application:
        name: kafka-demo
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=kafka_demo_idempotent_consumer
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema: kafka_demo_idempotent_consumer
        hibernate:
            ddl-auto: validate
        generate-ddl: false
    data:
        rest:
            detection-strategy: annotated
    flyway:
        schemas: kafka_demo_idempotent_consumer

kafka:
    bootstrap-servers: localhost:9092
    consumer:
        # Default to 30 seconds
        maxPollIntervalMs: 30000

server:
    port: 9001

kafkademo:
    id: demo
    thirdpartyEndpoint: http://localhost:9002/api/kafkaidempotentconsumerdemo/
    outboundTopic : "demo-outbound-topic"
